{
 "title": "Resilience4J Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "resilience4j_circuitbreaker_state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state"
    }
   ]
  },
  {
   "title": "resilience4j_circuitbreaker_slow_calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_slow_calls"
    }
   ]
  },
  {
   "title": "resilience4j_circuitbreaker_slow_call_rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_slow_call_rate"
    }
   ]
  },
  {
   "title": "resilience4j_circuitbreaker_failure_rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate"
    }
   ]
  },
  {
   "title": "resilience4j_circuitbreaker_calls_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_calls_total"
    }
   ]
  },
  {
   "title": "resilience4j_circuitbreaker_calls_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_calls_seconds_sum"
    }
   ]
  },
  {
   "title": "resilience4j_circuitbreaker_calls_seconds_max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_calls_seconds_max"
    }
   ]
  },
  {
   "title": "resilience4j_circuitbreaker_calls_seconds_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_calls_seconds_count"
    }
   ]
  },
  {
   "title": "resilience4j_circuitbreaker_buffered_calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls"
    }
   ]
  }
 ]
}