spring:
  application:
    name: movie-aggregator-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

info:
  app:
    name: Movie Aggregator Service

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,prometheus

eureka:
  client:
    enabled: true

feign:
  hystrix:
    enabled: false
